# Generated by Django 5.0.2 on 2024-07-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerece', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='\\Product-images'),
        ),
    ]
