# Generated by Django 5.0.2 on 2024-07-08 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerece', '0005_category_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category',
            new_name='category',
        ),
    ]
