# Generated by Django 5.0.2 on 2024-07-08 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerece', '0006_rename_category_category_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='title',
        ),
    ]
