# Generated by Django 5.0.2 on 2024-07-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerece', '0011_alter_product_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user_id',
            field=models.CharField(default=False, max_length=40),
        ),
    ]
