# Generated by Django 5.0.2 on 2024-07-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerece', '0012_cart_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
