# Generated by Django 5.0.2 on 2024-07-13 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerece', '0013_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user_id',
        ),
    ]
