# Generated by Django 5.0.2 on 2024-07-13 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerece', '0014_remove_cart_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
