# Generated by Django 5.0.2 on 2024-07-13 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerece', '0015_remove_cart_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
