# Generated by Django 5.0.2 on 2024-07-14 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerece', '0017_alter_product_price_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
