# Generated by Django 5.0.2 on 2024-07-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerece', '0018_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.PositiveIntegerField(blank=True, default='', null=True),
        ),
    ]
