# Generated by Django 5.0.2 on 2024-07-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerece', '0019_product_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
