# Generated by Django 5.0.2 on 2024-07-15 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerece', '0020_alter_product_sale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sale_price',
        ),
    ]
